# Generated by Django 3.0.5 on 2020-04-24 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='review_author',
        ),
    ]
